### ISSUE TITLE
Fehlender Inhalt

### ISSUE THREAD

**Issue by Niklas574** [DavidImmanuelSchwieder/Docker#1]
Guten Tag @DavidImmanuelSchwieder ,
Der Inhalt der README müsste erweitert werden.

**Comment by DavidImmanuelSchwieder** [comment]
wird noch überarbeitet

**Comment by DavidImmanuelSchwieder** [comment]
closed

**Comment by Niklas574** [comment]
Guten Tag @DavidImmanuelSchwieder  ,
Der Inhalt der README müsste immernoch erweitert werden.
